language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
- npm install
- npm test

addons:
  ssh_known_hosts: invisble.f4.htw-berlin.de

before_deploy:
- openssl aes-256-cbc -K $encrypted_111186c124b5_key -iv $encrypted_111186c124b5_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

after_success:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete-after --quiet $TRAVIS_BUILD_DIR/public travis@invisible.f4.htw-berlin.de:frontend
  on:
    branch: master
