sudo: true
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_111186c124b5_key -iv $encrypted_111186c124b5_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/rsa
- cat server.pub >> $HOME/.ssh/known_hosts
after_success:
  -   bash ./deploy.sh

#!/bin/bash
set -xe

if [ $TRAVIS_BRANCH == 'master' ] ; then
  eval "$ssh-agent -s)"
  ssh-add
  npm run build
  rsync -rq --delete --rsync-path="mkdir -p frontend $$ rsync" \
  $TRAVIS_BUILD_DIR/public travis@invisible.f4.htw-berlin.de:frontend
else
  echo "Not deploying, since this branch isn't master"
fi

