language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm install
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_111186c124b5_key -iv $encrypted_111186c124b5_iv
  -in travis_rsa.enc -out travis_rsa -d
